---
- name: Substrate Install | Install dependencies
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Substrate Install | Get latest release of a public repository
  become: false
  community.general.github_release:
    user: digitalnativeinc
    repo: standard-substrate
    action: latest_release
  when: substrate_node_version == 'latest'
  register: release
  delegate_to: 127.0.0.1

- name: Substrate Install | Get fact for release
  set_fact:
    substrate_node_version: "{{ release.tag }}"
  when: substrate_node_version == 'latest'

- name: Substrate Install | Download release
  get_url:
    url: "{{ substrate_node_source }}"
    dest: "{{ substrate_node_bin_dir }}/{{ substrate_node_bin_name }}"
    owner: "{{ substrate_node_user }}"
    group: "{{ substrate_node_group }}"
    mode: a+x
    backup: true
  register: release_download

- name: Substrate Install | Output file
  debug:
    msg: "{{ release_download.backup_file }}"
  when: release_download.changed
