---
- name: Substrate Install | Install dependencies
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Substrate Install | Get latest release of a public repository
  become: false
  community.general.github_release:
    user: digitalnativeinc
    repo: standard-substrate
    action: latest_release
  when: substrate_node_version == 'latest'
  register: release
  delegate_to: 127.0.0.1

- name: Substrate Install | Get fact for release
  set_fact:
    substrate_node_version: "{{ release.tag }}"
  when: substrate_node_version == 'latest'

- name: Substrate Install | Binary release download
  block:
    - name: Substrate Install | Download release
      get_url:
        url: "{{ substrate_node_source }}"
        dest: "{{ substrate_node_bin_dir }}/{{ substrate_node_bin_name }}"
        owner: "{{ substrate_node_user }}"
        group: "{{ substrate_node_group }}"
        mode: a+x
        backup: true
      register: release_download

    - name: Substrate Install | Backup file location
      debug:
        msg: "{{ release_download.backup_file }}"
      when: release_download.changed
  when:
    - '".tar.gz" not in substrate_node_source'

- name: Substrate Install | Archive release download
  block:
    - name: Substrate Install | Create tmp dir
      ansible.builtin.file:
        path: "/tmp/{{ substrate_node_bin_name }}"
        state: directory
        mode: "0755"
      register: tmp_folder

    - name: Substrate Install | Unarchive a file that needs to be downloaded
      ansible.builtin.unarchive:
        src: "{{ substrate_node_source }}"
        dest: "{{ tmp_folder.path }}/"
        remote_src: yes
        owner: "{{ substrate_node_user }}"
        group: "{{ substrate_node_group }}"
        list_files: true
      register: release_download

    - name: Substrate Install | Archive details
      debug:
        var: release_download.dest

    - name: Substrate Install | Move file
      ansible.builtin.copy:
        src: "{{ release_download.dest }}/plasm"
        dest: "{{ substrate_node_bin_dir }}/{{ substrate_node_bin_name }}"
        owner: "{{ substrate_node_user }}"
        group: "{{ substrate_node_group }}"
        remote_src: yes
        backup: true
        mode: a+x

    - name: Recursively remove directory
      ansible.builtin.file:
        path: /etc/foo
        state: absent

    - name: Substrate Install | Backup file location
      debug:
        msg: "{{ release_download.backup_file }}"
      when: release_download.changed
  when:
    - '".tar.gz" in substrate_node_source'
