---
- name: Substrate Ops | Rotate session keys
  block:
    - name: Substrate Session | Rotate Session key
      uri:
        url: "http://localhost:{{ substrate_node_rpc_port }}"
        method: POST
        body: >
          {"id":1, "jsonrpc":"2.0", "method": "author_rotateKeys", "params":[]}
        body_format: json
        status_code: 200
      register: rotate_keys_result

    - name: Substrate Session | Show session key
      debug:
        msg:
          - ==============================================================
          - Session key: "{{ rotate_keys_result.json.result | default('Undefined') }}"
          - ==============================================================
  tags:
    - never
    - rotate_keys

- name: Substrate Ops | Purge Chain
  block:
    - name: Substrate Purge | Substrate Stop
      ansible.builtin.systemd:
        state: stopped
        enabled: false
        name: "{{ substrate_node_bin_name }}"

    - name: Substrate Purge | Purge chain
      command: |
        {{ _substrate_node_bin_path }} purge-chain -y \
          {% if substrate_node_chain | length %}
          --chain {{ substrate_node_chain }} \
          {% endif %}
          --base-path {{ substrate_node_data_dir }}
  tags:
    - never
    - purge_chain

# requires additional logic
- name: Substrate Ops | Rollback
  block:
    - name: Substrate Rollback |
      ansible.builtin.systemd:
        state: stopped
        name: "{{ substrate_node_bin_name }}"
  tags:
    - never
    - rollback

- name: Substrate Ops | Create Local Chainspec
  block:
    - name: Substrate Ops | Generate spec
      command: |
        {{ _substrate_node_bin_path }} build-spec \
          --chain {{ substrate_node_chain }} \
          --raw \
          --disable-default-bootnode \
          > {{ substrate_node_bin_dir }}{{ substrate_node_chain }}.json

    - name: Substrate Ops | Fetch generated
      ansible.builtin.fetch:
        src: "{{ substrate_node_bin_dir }}/{{ item }}"
        dest: ./
      loop:
        - "para-{{ substrate_node_parachain_id }}-wasm"
        - "para-{{ substrate_node_parachain_id }}-wasm"
  tags:
    - never
    - chainspec

- name: Substrate Ops | Get help on commands
  block:
    - name: Substrate Ops | Query help
      command: |
        {{ _substrate_node_bin_path }} --help
      register: help
    - name: Substrate Ops | Show help command
      debug:
        var: help.stdout
  tags:
    - never
    - get_help

- name: Substrate Ops | Run custom command
  block:
    - name: Substrate Ops | Query help
      command: |
        {{ _substrate_node_bin_path }} {{ substrate_node_custom_command }}
      register: help
    - name: Substrate Ops | Show help command
      debug:
        var: help.stdout
  tags:
    - never
    - custom_command

- name: Substrate Ops | Generate collator genesis state/wasm
  block:
    - name: Substrate Ops | Export Genesis state
      command: |
        {{ substrate_node_bin_name }} export-genesis-state \
        --chain {{ substrate_node_chain }} \
        --parachain-id {{ substrate_node_parachain_id }} \
        > para-{{ substrate_node_parachain_id }}-genesis
      args:
        chdir: "{{ substrate_node_bin_dir }}"
    - name: Substrate Ops | export Genesis WASM
      command: |
        {{ substrate_node_bin_name }} export-genesis-wasm \
        --chain {{ substrate_node_chain }} \
        > para-{{ substrate_node_parachain_id }}-wasm
      args:
        chdir: "{{ substrate_node_bin_dir }}"
    - name: Substrate Ops | Fetch generated
      ansible.builtin.fetch:
        src: "{{ substrate_node_bin_dir }}/{{ item }}"
        dest: ./
      loop:
        - "para-{{ substrate_node_parachain_id }}-wasm"
        - "para-{{ substrate_node_parachain_id }}-wasm"
  tags:
    - never
    - export_collator_genesis

- name: Substrate Ops | Purge all
  block:
    - name: Substrate Purge All | Substrate Stop
      ansible.builtin.systemd:
        state: stopped
        enabled: false
        name: "{{ substrate_node_bin_name }}"

    - name: Substrate Purge All | Remove bin/data dir
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ _substrate_node_bin_path }}"
        - "{{ substrate_node_data_dir }}"
        - "/etc/logrotate.d/{{ substrate_node_bin_name }}"
        - "/var/log/{{ substrate_node_bin_name }}"

    - name: Substrate Purge All | Remove user
      ansible.builtin.user:
        name: "{{ substrate_node_user }}"
        state: absent
        remove: true

    - name: Substrate Purge All | Remove group
      ansible.builtin.group:
        name: "{{ substrate_node_group }}"
        state: absent
  tags:
    - never
    - purge_all
