---
- name: Substrate Postflight | Get node details
  uri:
    url: "http://localhost:{{ substrate_node_rpc_port }}"
    method: POST
    body: >
      {"id":1, "jsonrpc":"2.0", "method": "{{ item }}", "params":[]}
    body_format: json
    status_code: 200
  register: node_rpc_result
  with_items:
    - system_localPeerId
    - system_name
    - system_nodeRoles
    - system_version
    - system_chain
    - system_chainType
    - net_peerCount
    - system_name

- name: Substrate Postflight | Get public IP
  community.general.ipify_facts:
    timeout: 60
    validate_certs: true
  register: PUBLIC_IP
  ignore_errors: true

- name: Substrate Postflight | Backup public IP
  shell: |
    dig +short myip.opendns.com @resolver1.opendns.com
  register: BACKUP_PUBLIC_IP
  when: PUBLIC_IP.failed == true

- name: Substrate Postflight | Set fact for subsequent plays
  set_fact:
    peer_id: "{{ node_rpc_result.results[0].json.result }}"
    external_address: >-
      "/ip4/{{ PUBLIC_IP.ansible_facts.ipify_public_ip | default(BACKUP_PUBLIC_IP.stdout) }}/tcp/{{ substrate_node_p2p_port }}/p2p/{{ node_rpc_result.results[0].json.result }}"
    cacheable: true
  ignore_errors: true

- name: Substrate Postflight | Show output
  debug:
    msg:
      - ==============================================================
      - Data directory: "{{ substrate_node_data_dir | default('Undefined') }}"
      - Peer ID: "{{ node_rpc_result.results[0].json.result | default('Undefined') }}"
      - Node Name: "{{ node_rpc_result.results[1].json.result | default('Undefined') }}"
      - Node Role: "{{ node_rpc_result.results[2].json.result | default('Undefined') }}"
      - Node Version: "{{ node_rpc_result.results[3].json.result | default('Undefined') }}"
      - Chain: "{{ node_rpc_result.results[4].json.result | default('Undefined') }}"
      - Chain Type: "{{ node_rpc_result.results[5].json.result | default('Undefined') }}"
      - Peer Count: "{{ node_rpc_result.results[6].json.result | default('Undefined') }}"
      - ==============================================================
