---
- name: Substrate Postflight | Get node details
  uri:
    url: "http://localhost:{{ substrate_node_rpc_port }}"
    method: POST
    body: >
      {"id":1, "jsonrpc":"2.0", "method": "{{ item }}", "params":[]}
    body_format: json
    status_code: 200
  register: node_rpc_result
  with_items:
    - system_localPeerId
    - system_nodeRoles
    - system_version
    - system_chain
    - system_chainType
    - net_peerCount

- name: Substrate Postflight | Set fact for subsequent plays
  set_fact:
    peer_id: "{{ node_rpc_result.results[0].json.result }}"
    bootnode: >-
      "/ip4/{{ hostvars[inventory_hostname]['public_ip_address'] }}/tcp/\
      {{ substrate_node_p2p_port }}/p2p/{{ node_rpc_result.results[0].json.result }}"
    cacheable: true

- name: Substrate Postflight | Show output
  debug:
    msg:
      - ==============================================================
      - Backup file: "{{ _backup_path | default('Undefined') }}"
      - Data directory: "{{ substrate_node_data_dir | default('Undefined') }}"
      - Release version: "{{ substrate_node_latest_version | default(substrate_node_version) }}"
      - ==============================================================
      - Peer ID: "{{ node_rpc_result.results[0].json.result | default('Undefined') }}"
      - Node Role: "{{ node_rpc_result.results[1].json.result | default('Undefined') }}"
      - Node Version: "{{ node_rpc_result.results[2].json.result | default('Undefined') }}"
      - Chain: "{{ node_rpc_result.results[3].json.result | default('Undefined') }}"
      - Chain Type: "{{ node_rpc_result.results[4].json.result | default('Undefined') }}"
      - Peer Count: "{{ node_rpc_result.results[5].json.result | default('Undefined') }}"
      - ==============================================================
