- name: Substrate User | Set root user if substrate_node_use_existing_user is set to false
  set_fact:
    substrate_node_user: root
    substrate_node_group: root
  when:
    - not substrate_node_use_existing_user
    - substrate_node_use_root

- block:
    - name: Substrate User | Add system group
      ansible.builtin.group:
        name: "{{ substrate_node_group }}"
        system: true
        state: present

    - name: Substrate User | Add user
      ansible.builtin.user:
        name: "{{ substrate_node_user }}"
        group: "{{ substrate_node_group }}"

    - name: Substrate User | Adjust permissions for data dir
      ansible.builtin.file:
        path: "{{ substrate_node_data_dir }}"
        state: directory
        owner: "{{ substrate_node_user }}"
        group: "{{ substrate_node_group }}"
        mode: 0750
        recurse: yes
  when:
    - not substrate_node_use_existing_user
    - not substrate_node_use_root

- block:
    - name: Substrate User | Remove user
      ansible.builtin.user:
        name: "{{ substrate_node_user }}"
        state: absent
        remove: yes

    - name: Substrate Group | Remove group
      ansible.builtin.group:
        name: "{{ substrate_node_group }}"
        state: absent
  when: not substrate_node_use_existing_user
