- block:
    - name: Substrate User | Add system group
      ansible.builtin.group:
        name: "{{ substrate_node_group }}"
        system: true
        state: present

    - name: Substrate User | Add user
      ansible.builtin.user:
        name: "{{ substrate_node_user }}"
        groups:
          - "{{ substrate_node_group }}"
          - "adm"

    - name: Substrate User | Adjust permissions for data dir
      ansible.builtin.file:
        path: "{{ substrate_node_data_dir }}"
        state: directory
        owner: "{{ substrate_node_user }}"
        group: "{{ substrate_node_group }}"
        mode: 0750
        recurse: true
  when:
    - substrate_node_user is not "root"
    - substrate_node_group is not "root"
