---
name: Publish to Ansible Galaxy

on:
  release:
    types: [released]
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Galaxy Publish
        uses: 0x022b/galaxy-role-import-action@v1
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
